## Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia

os:
  - linux

julia:
  - 1.5

branches:
  only:
    - master
    - /^release-.*$/
    - /^v\d+\.\d+(\.\d+)?(-\S*)?$/

notifications:
  email: false

codecov: true
coveralls: true


jobs:
  include:
    - stage: "Documentation"
      julia: 1.5
      os: linux
      script:
        - julia --project=docs/ -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd())); Pkg.instantiate()'
        - julia --project=docs/ --color=yes docs/make.jl
      after_success: skip

